M48
; DRILL file {KiCad 9.0.6} date 2026-01-12T11:26:29-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-12T11:26:29-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.700
%
G90
G05
T1
X70.0Y-52.705
X70.0Y-126.365
X137.0Y-52.705
X137.0Y-126.365
M30
