M48
; DRILL file {KiCad 9.0.6} date 2026-01-12T10:47:32-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-12T10:47:32-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X37.7Y-56.6
X37.7Y-102.4
X137.0Y-56.6
X137.0Y-102.4
X245.1Y-56.6
X245.1Y-102.4
M30
